In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
# Leer el dataset
Hosp_sheet = pd.read_excel("datos.xls", sheet_name='Hospitales')
Hosp_sheet.head()

,Nombre Servicio de Salud,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto,Total Camas Críticas,Máxima cantidad de camas a aumetar,Costo de instalar una cama [MM$],Costo de operación anual de una cama [MM$],Costo diario GRD1 [MM$],Costo diario GRD2 [MM$],Costo diario GRD3 [MM$],Costo diario GRD4 [MM$],Costo diario GRD5 [MM$],Costo diario GRD6 [MM$],Costo diario GRD7 [MM$],Costo diario GRD8 [MM$],Costo diario GRD9 [MM$],Costo diario GRD10 [MM$]
0,Metropolitano Norte ...,Complejo Hospitalario San José,11,33,44,10,1407,47.2,0.593,0.509,0.367,0.492,0.524,0.405,0.571,0.474,0.498,0.305
1,Metropolitano Occidente ...,Hospital Adalberto Steeger (Talagante),6,11,17,5,1263,62.1,0.493,0.357,0.429,0.382,0.469,0.386,0.543,0.362,0.564,0.333
2,Metropolitano Occidente ...,Hospital Dr. Félix Bulnes Cerda,3,6,9,5,1310,65.9,0.580,0.325,0.375,0.409,0.561,0.362,0.328,0.314,0.536,0.436
3,Metropolitano Occidente ...,Hospital San Juan de Dios,29,47,76,30,1066,39.2,0.482,0.554,0.564,0.331,0.438,0.509,0.544,0.410,0.441,0.359
4,Metropolitano Occidente ...,Instituto Traumatológico Dr. Teodoro Gebauer,12,6,18,5,1433,55.5,0.407,0.449,0.468,0.433,0.573,0.392,0.409,0.391,0.418,0.334

In [15]:
# Pregunta 1: ¿Cuál opción corresponde al código que permite calcular el total de camas críticas para cada uno de
# los servicios de salud? 
Hosp_sheet[["Nombre Servicio de Salud", "Total Camas Críticas"]].groupby("Nombre Servicio de Salud").sum()

                                                    Total Camas Críticas
Nombre Servicio de Salud
Metropolitano Central                                                105
Metropolitano Norte                                                   44
Metropolitano Occidente                                              120
Metropolitano Oriente                                                137
Metropolitano Sur                                                    173
Metropolitano Sur Oriente                                            127

In [16]:
# 2. Pregunta 2: ¿Cuáles de los siguientes servicios de salud son los tres servicios que tienen más camas críticas?  
# Selecciona las tres respuestas que consideres correctas.
# Metro Sur, Metro Oriente, Metro Sur Oriente

In [17]:
# 3. Pregunta 3
# ¿Cuál de los siguientes códigos permite calcular el costo promedio diario de atención para el GRD4?
Hosp_sheet["Costo diario GRD4 [MM$]"].mean()

0.4484761904761904

In [21]:
#4.Pregunta 4: ¿Cuál cifra corresponde al promedio diario de pacientes que han llegado a la red en los últimos
# 10 días (desde el día 415 al día 424)?  
info_hist = pd.read_excel("datos.xls", sheet_name='Información Histórica')
info_hist

,Número de llegada,Hospital al que llega,GRD,Día de llegada,Día de salida,Estadia
0,1,Instituto Traumatológico Dr. Teodoro Gebauer,GRD3,1,4,3
1,2,Hospital Clínico San Borja-Arriarán,GRD7,1,5,4
2,3,Hospital Dr. Luis Tisné B.,GRD7,1,5,4
3,4,Hospital Dr. Exequiel González Cortés,GRD10,1,11,10
4,5,Hospital Barros Luco Trudeau,GRD6,1,6,5
...,...,...,...,...,...,...
65529,65530,Hospital Clínico San Borja-Arriarán,GRD2,424,428,4
65530,65531,Hospital Dr. Exequiel González Cortés,GRD9,424,429,5
65531,65532,Hospital Del Salvador,GRD10,424,434,10
65532,65533,Hospital de Enfermedades Infecciosas Dr. Lucio...,GRD3,424,427,3
65533,65534,Hospital de Urgencia Asistencia Pública Dr. Al...,GRD7,424,428,4

In [22]:
contador = 0
for i in info_hist['Día de llegada']:
    if i >= 415:
        contador += 1
print(contador/10)

154.5

In [24]:
# 5. Pregunta 5 ¿Cuál es el promedio del costo diario de resolución en clínica privada de los 3 GRDs más costos?  
GRD = pd.read_excel("datos.xls", sheet_name='GRD')
GRD

  ID GRD      Nombre GRD  Costo resolución en Clínica Privada [MM$]
0   GRD1       Coronario                                      7.917
1   GRD2        Hepático                                      3.417
2   GRD3    Respiratorio                                      2.915
3   GRD4           Renal                                      6.188
4   GRD5     Neurológico                                      6.782
5   GRD6  Traumatológico                                      4.881
6   GRD7       Esofágico                                      2.629
7   GRD8   Oftalmológico                                      6.720
8   GRD9    Circulatorio                                      5.524
9  GRD10      Intestinal                                      7.916

In [31]:
a = GRD['Costo resolución en Clínica Privada [MM$]'].sort_values(ascending=False)
a

0    7.917
9    7.916
4    6.782
7    6.720
3    6.188
8    5.524
5    4.881
1    3.417
2    2.915
6    2.629
Name: Costo resolución en Clínica Privada [MM$], dtype: float64

In [39]:
print((a[0]+a[9]+a[4])/3)

7.538333333333334

In [40]:
# 6.Pregunta 6: ¿Cuál de los siguientes códigos permite calcular la cantidad de días de estadía promedio por GRD
# para los pacientes ingresados en los últimos 10 días registrados en el archivo (y entonces, desde el día 415 al
# día 424)?  
info_hist

,Número de llegada,Hospital al que llega,GRD,Día de llegada,Día de salida,Estadia
0,1,Instituto Traumatológico Dr. Teodoro Gebauer,GRD3,1,4,3
1,2,Hospital Clínico San Borja-Arriarán,GRD7,1,5,4
2,3,Hospital Dr. Luis Tisné B.,GRD7,1,5,4
3,4,Hospital Dr. Exequiel González Cortés,GRD10,1,11,10
4,5,Hospital Barros Luco Trudeau,GRD6,1,6,5
...,...,...,...,...,...,...
65529,65530,Hospital Clínico San Borja-Arriarán,GRD2,424,428,4
65530,65531,Hospital Dr. Exequiel González Cortés,GRD9,424,429,5
65531,65532,Hospital Del Salvador,GRD10,424,434,10
65532,65533,Hospital de Enfermedades Infecciosas Dr. Lucio...,GRD3,424,427,3
65533,65534,Hospital de Urgencia Asistencia Pública Dr. Al...,GRD7,424,428,4

In [41]:
info_hist.loc[info_hist["Día de llegada"] >= 415].groupby("GRD").mean()

       Número de llegada  Día de llegada  Día de salida  Estadia
GRD
GRD1        64856.178808      419.874172     429.874172     10.0
GRD10       64812.290909      419.557576     429.557576     10.0
GRD2        64710.425806      419.006452     423.006452      4.0
GRD3        64709.131737      418.946108     421.946108      3.0
GRD4        64775.471014      419.362319     425.362319      6.0
GRD5        64819.895105      419.671329     423.671329      4.0
GRD6        64737.105590      419.136646     424.136646      5.0
GRD7        64746.628571      419.194286     423.194286      4.0
GRD8        64735.516779      419.147651     423.147651      4.0
GRD9        64725.191489      419.092199     424.092199      5.0

In [44]:

info_hist[info_hist["Día de llegada"] >= 415].groupby("GRD").mean()

       Número de llegada  Día de llegada  Día de salida  Estadia
GRD
GRD1        64856.178808      419.874172     429.874172     10.0
GRD10       64812.290909      419.557576     429.557576     10.0
GRD2        64710.425806      419.006452     423.006452      4.0
GRD3        64709.131737      418.946108     421.946108      3.0
GRD4        64775.471014      419.362319     425.362319      6.0
GRD5        64819.895105      419.671329     423.671329      4.0
GRD6        64737.105590      419.136646     424.136646      5.0
GRD7        64746.628571      419.194286     423.194286      4.0
GRD8        64735.516779      419.147651     423.147651      4.0
GRD9        64725.191489      419.092199     424.092199      5.0

In [61]:
# 7.Pregunta 7: ¿Qué cifra corresponde a la diferencia entre el menor y mayor costo, de operación anual de una cama
# para cada servicio de salud? 
minimo = Hosp_sheet['Costo de operación anual de una cama [MM$]'].min()
maximo = Hosp_sheet['Costo de operación anual de una cama [MM$]'].max()
maximo - minimo

29.499999999999993

In [63]:
# 8. Pregunta 8: ¿Cuántos pacientes llegaron a la red el día que llegaron más pacientes?
info_hist

,Número de llegada,Hospital al que llega,GRD,Día de llegada,Día de salida,Estadia
0,1,Instituto Traumatológico Dr. Teodoro Gebauer,GRD3,1,4,3
1,2,Hospital Clínico San Borja-Arriarán,GRD7,1,5,4
2,3,Hospital Dr. Luis Tisné B.,GRD7,1,5,4
3,4,Hospital Dr. Exequiel González Cortés,GRD10,1,11,10
4,5,Hospital Barros Luco Trudeau,GRD6,1,6,5
...,...,...,...,...,...,...
65529,65530,Hospital Clínico San Borja-Arriarán,GRD2,424,428,4
65530,65531,Hospital Dr. Exequiel González Cortés,GRD9,424,429,5
65531,65532,Hospital Del Salvador,GRD10,424,434,10
65532,65533,Hospital de Enfermedades Infecciosas Dr. Lucio...,GRD3,424,427,3
65533,65534,Hospital de Urgencia Asistencia Pública Dr. Al...,GRD7,424,428,4

In [66]:
info_hist['Día de llegada'].value_counts()

420    183
403    182
216    175
262    174
223    174
      ...
116    136
134    136
58     132
50     130
424     82
Name: Día de llegada, Length: 424, dtype: int64

In [71]:
# 9.Pregunta 9:¿Cuál código permite determinar el promedio del total de camas críticas para cada servicio de la red?
Hosp_sheet.head()

,Nombre Servicio de Salud,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto,Total Camas Críticas,Máxima cantidad de camas a aumetar,Costo de instalar una cama [MM$],Costo de operación anual de una cama [MM$],Costo diario GRD1 [MM$],Costo diario GRD2 [MM$],Costo diario GRD3 [MM$],Costo diario GRD4 [MM$],Costo diario GRD5 [MM$],Costo diario GRD6 [MM$],Costo diario GRD7 [MM$],Costo diario GRD8 [MM$],Costo diario GRD9 [MM$],Costo diario GRD10 [MM$]
0,Metropolitano Norte ...,Complejo Hospitalario San José,11,33,44,10,1407,47.2,0.593,0.509,0.367,0.492,0.524,0.405,0.571,0.474,0.498,0.305
1,Metropolitano Occidente ...,Hospital Adalberto Steeger (Talagante),6,11,17,5,1263,62.1,0.493,0.357,0.429,0.382,0.469,0.386,0.543,0.362,0.564,0.333
2,Metropolitano Occidente ...,Hospital Dr. Félix Bulnes Cerda,3,6,9,5,1310,65.9,0.580,0.325,0.375,0.409,0.561,0.362,0.328,0.314,0.536,0.436
3,Metropolitano Occidente ...,Hospital San Juan de Dios,29,47,76,30,1066,39.2,0.482,0.554,0.564,0.331,0.438,0.509,0.544,0.410,0.441,0.359
4,Metropolitano Occidente ...,Instituto Traumatológico Dr. Teodoro Gebauer,12,6,18,5,1433,55.5,0.407,0.449,0.468,0.433,0.573,0.392,0.409,0.391,0.418,0.334

In [72]:
Hosp_sheet[["Nombre Servicio de Salud", "Total Camas Críticas"]].groupby("Nombre Servicio de Salud").mean()

                                                    Total Camas Críticas
Nombre Servicio de Salud
Metropolitano Central                                              35.00
Metropolitano Norte                                                44.00
Metropolitano Occidente                                            30.00
Metropolitano Oriente                                              34.25
Metropolitano Sur                                                  34.60
Metropolitano Sur Oriente                                          31.75

In [79]:
# 10. Pregunta 10: ¿Cuál código permite determinar el valor del costo para instalar 3 camas nuevas y de las
# menos costosas- en cada servicio de salud?
Hosp_sheet.head()

,Nombre Servicio de Salud,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto,Total Camas Críticas,Máxima cantidad de camas a aumetar,Costo de instalar una cama [MM$],Costo de operación anual de una cama [MM$],Costo diario GRD1 [MM$],Costo diario GRD2 [MM$],Costo diario GRD3 [MM$],Costo diario GRD4 [MM$],Costo diario GRD5 [MM$],Costo diario GRD6 [MM$],Costo diario GRD7 [MM$],Costo diario GRD8 [MM$],Costo diario GRD9 [MM$],Costo diario GRD10 [MM$]
0,Metropolitano Norte ...,Complejo Hospitalario San José,11,33,44,10,1407,47.2,0.593,0.509,0.367,0.492,0.524,0.405,0.571,0.474,0.498,0.305
1,Metropolitano Occidente ...,Hospital Adalberto Steeger (Talagante),6,11,17,5,1263,62.1,0.493,0.357,0.429,0.382,0.469,0.386,0.543,0.362,0.564,0.333
2,Metropolitano Occidente ...,Hospital Dr. Félix Bulnes Cerda,3,6,9,5,1310,65.9,0.580,0.325,0.375,0.409,0.561,0.362,0.328,0.314,0.536,0.436
3,Metropolitano Occidente ...,Hospital San Juan de Dios,29,47,76,30,1066,39.2,0.482,0.554,0.564,0.331,0.438,0.509,0.544,0.410,0.441,0.359
4,Metropolitano Occidente ...,Instituto Traumatológico Dr. Teodoro Gebauer,12,6,18,5,1433,55.5,0.407,0.449,0.468,0.433,0.573,0.392,0.409,0.391,0.418,0.334

In [92]:
costo_camas = Hosp_sheet[["Nombre Servicio de Salud", "Costo de instalar una cama [MM$]"]].groupby("Nombre Servicio de Salud").min()
costo_camas["Costo 3 camas nuevas"] = costo_camas["Costo de instalar una cama [MM$]"]*3
costo_camas

,Costo de instalar una cama [MM$],Costo 3 camas nuevas
Nombre Servicio de Salud,,
Metropolitano Central,1256,3768
Metropolitano Norte,1407,4221
Metropolitano Occidente,1066,3198
Metropolitano Oriente,1056,3168
Metropolitano Sur,1051,3153
Metropolitano Sur Oriente,1028,3084